runtime: python39

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 302
    script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "beautifultrouble-4923d9842172.json"
